#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
missing=0

require_file() {
  local path="$1"
  if [[ ! -f "$repo_root/$path" ]]; then
    echo "Manca: $path" >&2
    missing=1
  fi
}

while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  require_file "$path"
done <<'EOF'
README.md
docker-compose.yml
docker-compose.ticketing.yml
docker-compose.telemetry.yml
docs/guida-studenti.md
docs/setup-laboratorio.md
docs/indice-materiali.md
docs/guida-operativa-piattaforme.md
docs/comandi-laboratorio-docker.md
docs/query-copia-incolla.md
docs/architettura-ticketing.md
docs/architettura-telemetria.md
manifest/materials.tsv
slides/blocks/block01_dominio_relazioni/block01_dominio_relazioni.pdf
slides/blocks/block02_chiavi_vincoli_integrita/block02_chiavi_vincoli_integrita.pdf
slides/blocks/block03_normalizzazione_schema/block03_normalizzazione_schema.pdf
slides/blocks/block03_normalizzazione_schema/block03_normalizzazione_schema_casi_studio.pdf
slides/blocks/block04_select_sql_base/block04_select_sql_base.pdf
slides/blocks/block04_select_sql_base/block04_select_sql_base_introduzione_sql.pdf
slides/blocks/block05_join_cardinalita/block05_join_cardinalita.pdf
slides/blocks/block05_join_cardinalita/block05_join_cardinalita_introduzione_join.pdf
slides/blocks/block06_aggregazioni_kpi/block06_aggregazioni_kpi.pdf
slides/blocks/block06_aggregazioni_kpi/block06_aggregazioni_kpi_introduzione_aggregazioni.pdf
slides/blocks/block07_ddl_dml_transazioni/block07_ddl_dml_transazioni.pdf
slides/blocks/block07_ddl_dml_transazioni/block07_ddl_dml_transazioni_introduzione_ddl_dml.pdf
slides/blocks/block08_subquery_set_logic/block08_subquery_set_logic.pdf
slides/blocks/block08_subquery_set_logic/block08_subquery_set_logic_introduzione_subquery.pdf
slides/blocks/block09_cte_viste_mantenibilita/block09_cte_viste_mantenibilita.pdf
slides/blocks/block10_window_functions/block10_window_functions.pdf
slides/blocks/block11_performance_explain_indici/block11_performance_explain_indici.pdf
slides/blocks/block12_capstone_query_design/block12_capstone_query_design.pdf
slides/blocks/block13_nosql_fondamenti/block13_nosql_fondamenti.pdf
slides/blocks/block13_nosql_fondamenti/block13_nosql_fondamenti_panoramica_nosql.pdf
slides/blocks/block14_nosql_scenari_modelli/block14_nosql_scenari_modelli.pdf
slides/blocks/block14_nosql_scenari_modelli/block14_nosql_scenari_modelli_architetture_polyglot.pdf
slides/blocks/block15_telemetria_mongodb_architettura/block15_telemetria_mongodb_architettura.pdf
slides/blocks/block16_telemetria_dashboard_capstone/block16_telemetria_dashboard_capstone.pdf
activities/README.md
activities/block01_dominio_relazioni/block01_dominio_relazioni_activity.pdf
activities/block02_chiavi_vincoli_integrita/block02_chiavi_vincoli_integrita_activity.pdf
activities/block03_normalizzazione_schema/block03_normalizzazione_schema_activity.pdf
activities/block03_normalizzazione_schema/block03_normalizzazione_schema_casi_studio_handout.pdf
activities/block03_normalizzazione_schema/block03_normalizzazione_schema_postgresql_docker.pdf
activities/block03_normalizzazione_schema/postgresql_docker_test.sql
activities/block04_select_sql_base/block04_select_sql_base_activity.pdf
activities/block04_select_sql_base/block04_select_sql_base_docker_exercises.pdf
activities/block04_select_sql_base/docker_exercises.sql
activities/block04_select_sql_base/block04_select_sql_base_introduzione_sql_handout.pdf
activities/block04_select_sql_base/introduzione_sql_examples.sql
activities/block05_join_cardinalita/block05_join_cardinalita_activity.pdf
activities/block05_join_cardinalita/block05_join_cardinalita_docker_exercises.pdf
activities/block05_join_cardinalita/docker_exercises.sql
activities/block05_join_cardinalita/block05_join_cardinalita_introduzione_join_handout.pdf
activities/block05_join_cardinalita/introduzione_join_examples.sql
activities/block06_aggregazioni_kpi/block06_aggregazioni_kpi_activity.pdf
activities/block06_aggregazioni_kpi/block06_aggregazioni_kpi_docker_exercises.pdf
activities/block06_aggregazioni_kpi/block06_aggregazioni_kpi_introduzione_aggregazioni_handout.pdf
activities/block06_aggregazioni_kpi/docker_exercises.sql
activities/block06_aggregazioni_kpi/introduzione_aggregazioni_examples.sql
activities/block07_ddl_dml_transazioni/block07_ddl_dml_transazioni_activity.pdf
activities/block07_ddl_dml_transazioni/block07_ddl_dml_transazioni_docker_exercises.pdf
activities/block07_ddl_dml_transazioni/block07_ddl_dml_transazioni_introduzione_ddl_dml_handout.pdf
activities/block07_ddl_dml_transazioni/docker_exercises.sql
activities/block07_ddl_dml_transazioni/introduzione_ddl_dml_examples.sql
activities/block08_subquery_set_logic/block08_subquery_set_logic_activity.pdf
activities/block08_subquery_set_logic/block08_subquery_set_logic_docker_exercises.pdf
activities/block08_subquery_set_logic/block08_subquery_set_logic_introduzione_subquery_handout.pdf
activities/block08_subquery_set_logic/docker_exercises.sql
activities/block08_subquery_set_logic/introduzione_subquery_examples.sql
activities/block09_cte_viste_mantenibilita/block09_cte_viste_mantenibilita_activity.pdf
activities/block10_window_functions/block10_window_functions_activity.pdf
activities/block11_performance_explain_indici/block11_performance_explain_indici_activity.pdf
activities/block12_capstone_query_design/block12_capstone_query_design_activity.pdf
activities/block13_nosql_fondamenti/block13_nosql_fondamenti_activity.pdf
activities/block13_nosql_fondamenti/activity.md
activities/block13_nosql_fondamenti/panoramica_comparativa_nosql.md
activities/block13_nosql_fondamenti/solution.md
activities/block14_nosql_scenari_modelli/block14_nosql_scenari_modelli_activity.pdf
activities/block14_nosql_scenari_modelli/activity.md
activities/block14_nosql_scenari_modelli/architetture_polyglot.md
activities/block14_nosql_scenari_modelli/solution.md
activities/block15_telemetria_mongodb_architettura/block15_telemetria_mongodb_architettura_activity.pdf
activities/block15_telemetria_mongodb_architettura/activity.md
activities/block15_telemetria_mongodb_architettura/solution.md
activities/block15_telemetria_mongodb_architettura/solution.js
activities/block16_telemetria_dashboard_capstone/block16_telemetria_dashboard_capstone_activity.pdf
activities/block16_telemetria_dashboard_capstone/activity.md
activities/block16_telemetria_dashboard_capstone/solution.md
activities/block16_telemetria_dashboard_capstone/solution.js
sql/00_schema_and_all_solutions_postgres.sql
sql/01_schema_seed_postgres.sql
sql/02_labs.sql
sql/03_solutions.sql
sql/query_copia_incolla.sql
sql/ticket_architecture_schema.sql
sql/ticket_collector_tick.sql
sql/ticket_architecture_dashboard_queries.sql
sql/ticket_load_generate.sql
sql/ticket_index_tradeoff.sql
nosql/README.md
nosql/telemetry_schema.js
nosql/telemetry_collector_tick.js
nosql/telemetry_dashboard_queries.js
EOF

if [[ "$missing" -ne 0 ]]; then
  echo "Verifica fallita." >&2
  exit 1
fi

echo "Verifica completata: materiali minimi presenti."
